site_name: EDM (pyEDM, rEDM)
theme: 
    name: readthedocs
extra_css: [extra.css]

plugins:
- mknotebooks

markdown_extensions:
- attr_list

nav:
- Home : index.md
- Getting Started :
    - Installation : installation.md
    - EDM Framework : edm_intro.md
- Documentation :
    - Embedding : embedding_parameters.md
    - Parameters : parameters.md
    - EDM Functions : edm_functions.md
- EDM Algorithms :
    - Basic EDM Examples : basic_examples.ipynb
    - EDM Algorithms in Depth : algorithms_in_depth.md
    - S-map : SMap_Demo.ipynb
    - Custom Solvers : solvers_demo.ipynb
    - Conditional Embedding : cond_emb_demo.ipynb
