site_name: EDM (pyEDM, rEDM)
theme: 
    name: readthedocs
extra_css: [extra.css]

nav:

- Home : index.md
- Getting Started :
    - Installation : installation.md
    - EDM Framework : edm_intro.md
- Documentation : 
    - EDM Functions : edm_functions.md
- EDM Algorithms :
    - Examples : algorithms_high_level.md
    - EDM Algorithms in Depth : algorithms_in_depth.md
